export const INIT_SVG_ANIMATION_TIME = '1s';
export const START_ANIMATION_TIME = '0.4s';
export const LETTER_INIT_ANIMATION_DELAY = '0.02s';
export const LETTER_INIT_ANIMATION_TIME = '0.02s';
export const UNDERLINE_INIT_ANIMATION_TIME = '0.2s';
const UNDERLINE_INIT_ANIMATION_DELAY_AFTER_LETTERS = '0.2s';
const MENU_INIT_ANIMATION_DELAY_AFTER_UNDERLINE = '0s';

export const LOGO_UNDERLINE_INIT_DELAY = `calc(${INIT_SVG_ANIMATION_TIME} +  20 * ${LETTER_INIT_ANIMATION_DELAY} + ${UNDERLINE_INIT_ANIMATION_DELAY_AFTER_LETTERS})`;
export const MENU_INIT_ANIMATION_DELAY = `calc(${INIT_SVG_ANIMATION_TIME} + 20 * ${LETTER_INIT_ANIMATION_DELAY} +  ${UNDERLINE_INIT_ANIMATION_DELAY_AFTER_LETTERS} + ${MENU_INIT_ANIMATION_DELAY_AFTER_UNDERLINE} )`;



// Services

// Services Content

export const SERVICE_CONTENT_SELECTION_ANIMATION_TIME = '0.7s';
export const SERVICE_CONTENT_SELECTION_ANIMATION_DELAY = '0.2s';

export const SERVICE_CONTENT_DESELECTION_ANIMATION_TIME = '0.7s'



// Services Card


export const SERVICE_CARD_HOVER_ANIMATION_TIME = '0.2s';

export const SERVICE_CARD_SELECTION_ANIMATION_TIME = '0.3s';


export const SERVICE_CARD_DESELECTION_ANIMATION_TIME = '0.3s';
export const SERVICE_CARD_DESELECTION_ANIMATION_DELAY = '0.7s';

export const SERVICE_CARD_START_ANIMATION_TIME = '0.2s';
export const SERVICE_CARD_START_ANIMATION_DELAY_STEP = '0.15s';
export const SERVICE_CARD_START_ANIMATION_DELAY = '0.2s';

export const totalDeselectionAnimationTime = 995;
export const totalSelectionAnimationTime = 900;